### ISSUE TITLE
Not sensitive to Logged in

### ISSUE THREAD

**Issue by pbrocks** [strangerstudios/pmpro-signup-shortcode#20]
Both the signup button and login link show even if signed in

![Alt text](https://monosnap.com/image/HRoZ9j18y6SxBKv6FuFNrPCzspmeWz.png)

**Comment by kimcoleman** [comment]
In this case, the ‘sign up now’ button is the checkout button so that should be showing. Clicking that button applies the level that the signup shortcode is attached to. 

I will assign this to myself and make sure that that ‘log in’ link doesn’t appear.

**Comment by kimcoleman** [comment]
Tested and this does not appear to be an issue. It may be an issue on the Memberlite Elements version of this shortcode.
