### ISSUE TITLE
FEATURE REQUEST: Support Google Analytics tracking

### ISSUE THREAD

**Issue by greathmaster** [strangerstudios/pmpro-signup-shortcode#22]
If a user is redirected to the referrer after sign-up, they never arrive on the confirmation page. This means the sign-up is not passed to Google analytics tracking.

**Comment by kimcoleman** [comment]
If you are using goals for the Signup Shortcode, you could add additional endpoints in your goal tracking. I do not see how we would support this use case in this Add On.
