### ISSUE TITLE
Save signup field values if user abandons checkout page

### ISSUE THREAD

**Issue by hbcondo** [strangerstudios/pmpro-signup-shortcode#23]
> [If the level is not free, the user will be taken to the membership checkout page to enter billing information](https://www.paidmembershipspro.com/streamline-membership-checkout-with-the-signup-shortcode-add-on-email-only-signup-redirect-to-referrer-and-popup-integration/)

It appears that if a user enters their email / username / password in the form the signup shortcode genereates for a paid level, the user is indeed redirected to the checkout page. If the user abandons the checkout page, the signup info entered is not saved. **Can PMP verify if this behavior is intended or not?** It would be very nice to be able to contact the user after an abandonment.

**Comment by kimcoleman** [comment]
If the user is not created on submitting the signup shortcode form, no user details are saved when they redirect to the checkout page.

We are exploring other ways to handle cart abandonment which would be either integration with a third party or another enhancement Add On outside functionality of this plugin.
