### ISSUE TITLE
Custom fields not showing on sign up page when restricted to a level

### ISSUE THREAD

**Issue by femiyb** [strangerstudios/pmpro-signup-shortcode#25]
Steps to recreate the issue:

- Create a custom field using RH
- Set the field to only display for a level
- Set up a signup shortcode to display sign up for that level

Issue: The signup shortcode doesn't show the custom field.

**Comment by MaryOJob** [comment]
Can recreate this. Same steps as above.

For moderators only: https://www.paidmembershipspro.com/forums/topic/add-custom-field-to-shortcode-signup/

**Comment by kimcoleman** [comment]
this is fixed in https://github.com/strangerstudios/pmpro-signup-shortcode/pull/30
