### ISSUE TITLE
Sign Up button refreshes page instead of redirects to new page

### ISSUE THREAD

**Issue by madisonBLNKPG** [strangerstudios/pmpro-signup-shortcode#27]
Hi,
I'm using this shortcode in a wordpress website I'm building. As listed in the title, I'm having issues with a new user being redirected to a page once they fill out the sign up form and click Sign Up. Instead of redirecting them, the form is cleared and the page refreshes. It doesn't even save the information they put in, as they don't get an email and the information doesn't even show up in the backend for me. This is the shortcode I currently have placed on the page: [pmpro_signup submit_button="SIGN UP" level="1" login="1" redirect="https://seedarchitects.wpengine.com/sign-up-confirmation/"]
Can someone tell me what could be going wrong? I'm not super savvy with this kind of stuff.
Thanks!

**Comment by kimcoleman** [comment]
Please open a ticket in our support area (Plus membership required) for support with this issue. I have tested a similar shortcode with a redirect page and there is no issue with redirection.

See: https://www.paidmembershipspro.com/support/
