### ISSUE TITLE
custom_fields true is not displaying fields created with user fields

### ISSUE THREAD

**Issue by kimwhite** [strangerstudios/pmpro-signup-shortcode#43]
**Describe the bug**
We want to display my User Fields on my signup shortcode. `custom_fields="true"` should display them but does not.
custom_fields works for Custom fields made with the RH code, but not the new user fields feature.

**To Reproduce**
1. Intall Signup Shortcode
2. Create User Fields
3. add `custom_fields="true"` to your shortcode - `[pmpro_signup level="1" custom_fields="true"]`
4. User Fields should appear on the form but do not.
<img width="1029" alt="Screen Shot 2022-08-29 at 3 15 42 PM" src="https://user-images.githubusercontent.com/8083630/187280777-606b4c08-c482-4c63-867f-6969a133b559.png">

**Expected behavior**
User Fields should appear under default fields.

<img width="709" alt="Screen Shot 2022-08-29 at 3 16 04 PM" src="https://user-images.githubusercontent.com/8083630/187280659-b70f2011-5224-4af0-8c33-ee991705b23a.png">

**Isolating the problem (mark completed items with an [x]):**
- [x ] I have deactivated other plugins and confirmed this bug occurs when only Paid Memberships Pro plugin is active.
- [x] This bug happens with a default WordPress theme active or [Memberlite](https://wordpress.org/themes/memberlite/).
- [x ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
WordPress 6.0.1
PMPro 2.9.3
```
</details>

**Comment by kimwhite** [comment]
You can use this now to add them:
`add_action( 'pmpro_signup_form_before_submit', 'pmpro_checkout_boxes_fields' );`

**Comment by MaryOJob** [comment]
This line of code works @kimwhite, thank you.
For Moderators Only: #451648
