### ISSUE TITLE
Would love the ability to choose to repeat the email field only

### ISSUE THREAD

**Issue by dvozov** [strangerstudios/pmpro-signup-shortcode#50]
**Is your feature request related to a problem? Please describe.**
There is no actual _problem_ with the way it is now. My thinking, however, is that as long as a customer uses the correct email address, they can always make a new password.

**Describe the solution you'd like**
Checkout fields are always friction points, and there's no way around that. Reducing the need to enter their password twice is a small concession to reduce a bit of customer-side work. Honestly, the more I talk about it, the less crucial it seems, lol. 

**Describe alternatives you've considered**
Being able to choose between repeating both (the previous version) and repeating none (the update), I'd choose repeat none. 

**Additional context**
Thanks much :)

**Comment by andrewlimaza** [comment]
Thanks for this @dvozov, you can use the attribute `confirm_password="false"` within your shortcode to hide this option. If you need more help with this, please do not hesitate to reach out to our support team via www.paidmembershipspro.com/support.

You may find the full list of available attributes here - https://www.paidmembershipspro.com/add-ons/pmpro-signup-shortcode/

I am going to close this issue on GitHub as it seems to be resolved.

**Comment by dvozov** [comment]
Hi Andrew, and thanks for the reply. It's been so long since I added what I
intended as a feature request - not a request for support - that I've kinda
forgotten why, lol. However, I'll keep your email and revisit how we have
our pages set up to see how I can utilize the info you've provided.

Much appreciation,

Deon :)
