### ISSUE TITLE
Adds password field even if membership level was changed

### ISSUE THREAD

**Issue by barocsi** [strangerstudios/pmpro-signup-shortcode#6]
Even member is created, when level is changed this plugin simply adds the md5 password to the email !!email!! template...
https://github.com/strangerstudios/pmpro-email-templates/issues/13

**Comment by andrewlimaza** [comment]
Thank you for opening an issue, could you please explain on how to recreate this?

The signup shortcode is for new members to signup for a membership level without reaching the checkout page (for free levels).

**Comment by ideadude** [comment]
I followed the link to the issue on the email templates repo and it seems like this might be via custom code. Going to close the issue here and follow up on the email template repo.
